### ISSUE TITLE
选择文件的时候，列表里没有，把文件放到最近下载文件夹里，也看不到

### ISSUE THREAD

**Issue by selai** [x-falcon/Virtual-Hosts#1]

**Comment by x-falcon** [comment]
软件调用的是系统自带的文件浏览器，这个浏览器确实很鸡肋，查找文件难，
你试试看多找找，应该是能找到的，或者放到根目录试试 @selai

**Comment by x-falcon** [comment]
![a](https://user-images.githubusercontent.com/5160100/27279467-45f5f9a2-5517-11e7-9922-42c5289d52f9.png)
