### ISSUE TITLE
Last release lacks signatures

### ISSUE THREAD

**Issue by IzzySoft** [x-falcon/Virtual-Hosts#10]
Getting the error

    ERROR: Found no signing certificates on app-Github-release.apk

Checking the file, indeed the `META-INF` folder is missing in the `.apk`. Could you please upload a fixed version? Thanks!

**Comment by x-falcon** [comment]
@IzzySoft has fix that  , thank you for reminding

**Comment by IzzySoft** [comment]
@x-falcon [worked](https://apt.izzysoft.de/fdroid/index/apk/com.github.xfalcon.vhosts), thanks!

PS: Feel free to include that link on your "front page", works with the F-Droid client :wink:
