### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by alexanderadam** [x-falcon/Virtual-Hosts#11]
It would be wonderful if Virtual-Hosts could be added to the _official_ [F-Droid repositories](https://f-droid.org/packages/).

AFAIK it's [a bit more complicated to have it published](https://f-droid.org/docs/FAQ_-_App_Developers/#how-do-i-get-my-app-included) but it's much better to have it in the official repositories [than having to trust another party like IzzySoft in his repository](https://github.com/x-falcon/Virtual-Hosts/issues/10#issuecomment-326653230).

Thank you in advance and have a nice day!

**Comment by alexanderadam** [comment]
Did you intentionally close the issue without writing anything?

**Comment by x-falcon** [comment]
Unfortunately, I thought it was advertising, and send by robot.

**Comment by alexanderadam** [comment]
It wasn't 🤖 
I'm promise that I'm totally human 😆 
And asking to publish your App in a free and non-profit repository wouldn't be very robotic, wouldn't it? 😄

**Comment by x-falcon** [comment]
How to publish it? 
What i need  to do?
