### ISSUE TITLE
For help,why virtual-Hosts not work on my Android 10?

### ISSUE THREAD

**Issue by itmayi** [x-falcon/Virtual-Hosts#115]
The hosts file is like this:
`10.79.10.233  xxxweb.com`

After i switch the button, and test for xxxweb.com, there are some errors:
`ping xxxweb.com`
`ping: unknown host xxxweb.com`

**Comment by x-falcon** [comment]
Is private dns settimg ?

**Comment by itmayi** [comment]
Yeah, Following your prompt, I found that the private dns was enabled. And after I turned it off, it is fine now. Thank you so much!
