### ISSUE TITLE
Use Virtual Hosts with Tasker

### ISSUE THREAD

**Issue by stefaanbolle** [x-falcon/Virtual-Hosts#12]
Nice app, works like a charm. Therefore I donated for it.
Is it possible to use Use Virtual Hosts with Tasker?
I want to activate Use Virtual Hosts when connected to home wifi and deactivate when not.
My phone is not rooted.
Any help would be welcome.

**Comment by x-falcon** [comment]
I'll need to know about Tasker before I can help you.
please wait patiently

**Comment by stefaanbolle** [comment]
Thanks!

**Comment by x-falcon** [comment]
The new version has been released, please try it.
You need  add launch parameter ( "on" or "off") in the Data option.
"on" mean start app, "off" mean stop app.

Help link (https://raw.githubusercontent.com/x-falcon/tools/master/vhosts-tasker-help.png)

**Comment by stefaanbolle** [comment]
Works very well for me! Thanks a lot for your superfast support! Much appreciated.
And oc course  I wish you a merry Christmas.

**Comment by x-falcon** [comment]
Merry Christmas.
