### ISSUE TITLE
在UC浏览器并不起作用

### ISSUE THREAD

**Issue by philohistoria** [x-falcon/Virtual-Hosts#13]
非常好用的app! 但是我在使用UC 浏览器的时候，virtual hosts 并不能屏蔽host中的网站（其他浏览器正常）。不知道是不是因为UC有预加载的原因？

**Comment by x-falcon** [comment]
应该是uc浏览器流量节省功能导致的，可以尝试关闭流量节省功能

**Comment by x-falcon** [comment]
应该是uc浏览器云加速功能导致的，可以尝试关闭云加速

**Comment by Babar-Bashir** [comment]
UC browser is using Data Compression/Data Saving mechanism.

**Comment by Babar-Bashir** [comment]
When you use Data Saver, most of your web traffic goes through their servers before being downloaded to your device. Less data gets downloaded to your device, because their servers will compress it.

**Comment by x-falcon** [comment]
Surprisingly, you know uc so well @Babar-Bashir
