### ISSUE TITLE
Importing project gives an error

### ISSUE THREAD

**Issue by sadatdaniel** [x-falcon/Virtual-Hosts#17]
I tried to import the project on Android Studio. It gives me this error. Am I missing something?

Error:C:\Users\daniel\.gradle\wrapper\dists\gradle-4.0.2-all\680wmhe205zg4atnbsmvvt28p\gradle-4.0.2-all.zip (The system cannot find the file specified).

**Comment by sadatdaniel** [comment]
Apologies. Most of the problems were solved by following the suggestions of Android studio. It had to download some libraries I think. 

Later it had one error and five warnings. 
The error notice was this, 

> All flavors must now belong to a named flavor dimension. Learn more at https://d.android.com/r/tools/flavorDimensions-missing-error-message.html

It was solved by adding this,

```

android { 
    ...
    flavorDimensions "default"
    ...
}
```

The five warnings were,

> 
> Configuration 'compile' is obsolete and has been replaced with 'implementation'.
> It will be removed at the end of 2018
> 
> 
> Configuration 'androidTestApi' is obsolete and has been replaced with 'androidTestImplementation'.
> It will be removed at the end of 2018
> 
> 
> Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation'.
> It will be removed at the end of 2018
> 
> 
> Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'.
> It will be removed at the end of 2018
> 
> 
> Configuration 'androidTestCompile' is obsolete and has been replaced with 'androidTestImplementation'.
> It will be removed at the end of 2018
> 

In the end, gradle build finished successfully.

Thanks for this awesome project. And forgive me if it was wrong for me to create an issue.

**Comment by x-falcon** [comment]
that's good.
If no thing, please close the issue.
