### ISSUE TITLE
stuck on browsing

### ISSUE THREAD

**Issue by Babar-Bashir** [x-falcon/Virtual-Hosts#2]
the app installs but whatever internet request (lets say google search for example) wont process.
Am not sure why it is so

**Comment by x-falcon** [comment]
please try restart app. and hope  provide logcat info, if you can.
 So we can improve it.

**Comment by txlong** [comment]
今天测试也不行，不能跳转指定IP，我的hosts内容为：
119.75.217.109 a.com
119.75.217.109 m.a.com
119.75.217.109 w.m.a.com

**Comment by x-falcon** [comment]
@txlong 刚刚测试了一下，是可以的，
![screenshot_20170628-084358](https://user-images.githubusercontent.com/5160100/27615910-4309f522-5bde-11e7-9fae-a5afe66f427c.jpg)

**Comment by txlong** [comment]
你好，我是app加载hosts文件，然后浏览器访问a.com，重定向了，但是没有打开指定IP 119.75.217.109页面(百度)。感谢回答

**Comment by x-falcon** [comment]
@txlong app运行正常就好。这样做的确是无法访问百度的，由于http header Host字段将会是a,com，百度会验证的
