### ISSUE TITLE
Does not block http traffic

### ISSUE THREAD

**Issue by HuxburyQuinn** [x-falcon/Virtual-Hosts#22]
Virtual Host Git hub source file: 
https://github.com/x-falcon/Virtual-Hosts/releases

Tested on Samsung Galaxy S4 Android 5.0.1
Tested on Oppo R11 Android 7.1.1

Created hosts file on the device using text editor.
Testing blocking URL   apple.com 
17.172.224.47        apple.com
17.178.96.59          apple.com
17.142.160.59        apple.com

Still able to access apple.com website for every browser on each device.

The link on your site to the sample host file is broken

I may have set up my hosts file incorrectly

Please advise

**Comment by Laicure** [comment]
You may want to add "www.apple.com" in your list.

**Comment by x-falcon** [comment]
@HuxburyQuinn 
try  use this if you want block apple
0.0.0.0 apple.com
0.0.0.0 apple.com
0.0.0.0 apple.com
