### ISSUE TITLE
Unable to browse local

### ISSUE THREAD

**Issue by plnkeye21** [x-falcon/Virtual-Hosts#24]
When selecting a host file I can select the 3 lines in the upper left, a window slides out from the side but I cannot move the highlighted item to the internal drive. When I move up or down the unfocused window scrolls through files on the external drive that for some reason the directory is pointed to. I'm trying to switch the directory and browse to the internal drive of an Nvidia Shield TV. I have a host file on the root of the internal drive and want to point to this file.

**Comment by 10pmStalker** [comment]
Exact same issue on Nvidia Shield. Hoping it can be resolved

**Comment by x-falcon** [comment]
@plnkeye21 @10pmStalker  Please try long click the select host file button, then you can use online hosts file by input url.
You can  put your hosts file to github,  when need change hosts,  just change it on github , and click down again.

**Comment by 10pmStalker** [comment]
Tried that. It turns green but still constant errors in lazyman. There's no way to manually apply your own file anymore?

**Comment by plnkeye21** [comment]
I've honestly got no clue how to do that. No idea how github works. Plus this doesn't really answer my question, why can I not use a function you included in the application?

**Comment by 10pmStalker** [comment]
I think it has something to do with Android 8.0

**Comment by 10pmStalker** [comment]
@x-falcon I'm trying to set it up on built in Android TV. What should I be doing on this screen? I tried every option and nothing works.

https://i.imgur.com/IdHgjNsh.jpg

**Comment by x-falcon** [comment]
@10pmStalker  1,click from internet -> 2,click confirm  -> 3,click the big switch. Then it will take effect.
You can use  ping command  to check.

**Comment by x-falcon** [comment]
@plnkeye21 Can you make a screenshot of the problem?Maybe I didn't understand the mistakes you met.

**Comment by plnkeye21** [comment]
https://imgur.com/a/mUHfIxg I can't control this menu to select "SHIELD". It automatically defaults to an external drive, so I select the 3 lines in the upper left and get this menu. However when I scroll up or down it doesn't highlight any of the selections in the menu, it controls the window behind this menu and selects items/files from the external drive. I'm simply trying to move the highlighted item here to the internal drive where I have a host.txt.

**Comment by 10pmStalker** [comment]
@x-falcon I did all that. Hooked up a mouse to click the big switch, it's green but still nothing but errors in lazyman. "update your hosts file to point to..."

**Comment by plnkeye21** [comment]
@10pmStalker how did you connect a mouse? Did it have to be wired USB? Wireless doesn't seem to be working for me. What's the full procedure you're doing please. Trying to get it working for LazyMan also.

**Comment by plnkeye21** [comment]
@10pmStalker Got it! Had to use a wired mouse. @x-falcon Definitely need to look at that on your next build. You can't navigate that menu without a mouse (wired).

**Comment by 10pmStalker** [comment]
@plnkeye21 did you manually select the txt file or did you use the auto download feature?

**Comment by plnkeye21** [comment]
Manually. I hit 'select host file' (did not long press it), and browsed to the SHIELD internal drive and selected the txt file and hit open. It returned me to the main screen and the switch was in the 'up' position and green. Tested LazyMan (Angel game is on) successfully!

**Comment by 10pmStalker** [comment]
Yeah same, was hoping you somehow did it the other way. Shield is the only android system that will let you browse. Nexus player won't even let you browse for a file.

**Comment by 10pmStalker** [comment]
@x-falcon is there any way you could make a quick video on how you're enabling it by hitting the download button? I don't get why it's not working. Is the url not correct maybe?

**Comment by x-falcon** [comment]
@10pmStalker   I see ,  you didn't enter your url, the default url  just for test,  you need to enter your url.
Here are some, you can refer to，https://github.com/StevenBlack/hosts.
Prompt, the url on github must start with **raw**.  , 
![default](https://user-images.githubusercontent.com/5160100/43326391-53c133be-91eb-11e8-94de-5f227157738b.PNG)
I will record a small video this weekend to explain how to use it.

**Comment by 10pmStalker** [comment]
@x-falcon that explains a lot, thank you. Could you copy and paste a link that would work? I'm still pretty confused on what will work. Been typing links with the remote and it's brutal haha

**Comment by 10pmStalker** [comment]
Alright so I got it on the Android TV with help from reddit. Simply added http://bit.ly/lmhosts then manually flipped the switch which you need a wired mouse to do.

I have a problem since the nexus player has no USB port, I can't manually flip the switch on that. It's not a big deal, got it working on 2 devices for now. Support to flip that switch without a mouse would be awesome. Thanks for everything @x-falcon

**Comment by x-falcon** [comment]
I'll fix this problem. It's caused by incompatible buttons.
