### ISSUE TITLE
Comments do not seem to work

### ISSUE THREAD

**Issue by shawac** [x-falcon/Virtual-Hosts#25]
I've encountered this weird issue days ago, demonstrated as follows:

Initially, I wrote the following lines in hosts file:
```
[Correct IP]    accounts.pixiv.net
#127.0.0.1      accounts.pixiv.net
```

Normally accounts.pixiv.net should be accessible, as the second line has been commented out (#). However, in my case I couldn't visit accounts.pixiv.net, and using ping in Termux returned 127.0.0.1, which meant the comment failed to work.

Then I removed the second line from hosts file, and immediately accounts.pixiv.net was accessible.

I'm not sure whether this problem is specific to my environment, or only occurs with this particular website. But I genuinely hope that you could look into this strange issue.

**Comment by x-falcon** [comment]
this maybe a bug,  I will fix it

**Comment by x-falcon** [comment]
@shawac the bug has fix. please test

**Comment by shawac** [comment]
After a bit testing, I think Version 2.0.2 has fixed this issue. Now comments work as normal.
Thanks!
