### ISSUE TITLE
VPN is bypassed on Android Pie

### ISSUE THREAD

**Issue by pplante** [x-falcon/Virtual-Hosts#27]
On my Pixel with v9.0 the VPN seems to be ignored entirely.  I have a hosts file with 67k entries that have no effect.  Any ideas?

**Comment by x-falcon** [comment]
May be incompatible with 9.0, I will review and fix this problem

**Comment by AndyWhittaker** [comment]
> On my Pixel with v9.0 the VPN seems to be ignored entirely. I have a hosts file with 67k entries that have no effect. Any ideas?

I have a recently upgraded OnePlus 6 running Android Pie and this is doing the same. It's shocking to see adverts again :-(

**Comment by x-falcon** [comment]
@AndyWhittaker  which adverts   you see or what's app or page？ please provide specific circumstances.
It's convenient for me to find problems.

**Comment by AndyWhittaker** [comment]
Prior to upgrading to Android 9, I saw no adverts. However, after upgrading it appears that my hosts file is being ignored, i.e. It does not matter if Virtual Hosts is enabled or not.

**Comment by x-falcon** [comment]
@AndyWhittaker Please reinstall the app for test. If it still doesn't work， please tell me where is the advertisement ，on the web page or in app?

**Comment by AndyWhittaker** [comment]
Uninstalled it and re-installed it... All OK! 😁 So happy - thanks!

**Comment by x-falcon** [comment]
@AndyWhittaker thank you.
@pplante please reinstall the app or clear the app data. then it will be ok

**Comment by AndyWhittaker** [comment]
Stop press, my set up is still showing adverts - they were being blocked by
my pi-hole blocker on my home broadband.

I've now gone out and about, adverts are being displayed. They turn up on
Web pages.

**Comment by pplante** [comment]
I tired the entire instructions on that link, including the DNS cache clearing. I still see ads in chrome and other apps on my phone.
