### ISSUE TITLE
Feature suggestion: merge and optimise hosts file

### ISSUE THREAD

**Issue by mgillespie** [x-falcon/Virtual-Hosts#3]
Finding a good adblock hosts file is easy enough, but they are usually setup for Windows and don't support wildcard hosts.  It would be nice if this app merged and optimised on import.

**Comment by x-falcon** [comment]
thank you for suggestion，in fact, we have already considered this question.
For the time being，you can try this tool  [](https://github.com/x-falcon/Virtual-Hosts/blob/master/hosts_to_wildcard.py)
