### ISSUE TITLE
unable to surf web or access apps

### ISSUE THREAD

**Issue by chachastars** [x-falcon/Virtual-Hosts#30]
Hi, I've been using Virtual host for quite some time and had no issue on my Samsung note 8, however recently i change to Vivo Nex S and tried to use virtual host, whenever i turn on the VPN i am unable to surf the web or access any apps. It shows site cannot be reach when i tried to open any website and i tried to disable the chrome DNS but it doesn't works.

**Comment by kitkatloyalist** [comment]
After installing Bromite and Firefox report if there are problems using the interweb with either

**Comment by chachastars** [comment]
I installed both bromite and Firefox, now I can surf the net and use my apps using virtual host, thank you so much for your help.
