### ISSUE TITLE
Virtual Host system file browser not found

### ISSUE THREAD

**Issue by firepoi27** [x-falcon/Virtual-Hosts#31]
I have been using a Kodi Add on that requires me to use Virtual Host.  I have it all working fine on one android product but not the new one.  When I go to Virtual Hosts to select the root file it says "System File Browser not found."  I was using ES File explorer but uninstalled that, also uninstalled Virtual Hosts.  Have Root Explorer Installed and reinstalled Virtual Hosts through that, but still get the same error.  I am sure it is something small I am missing but any help would be appreciated.

**Comment by firepoi27** [comment]
How long do you need to click for a long click?  Held down that button for a few minutes but nothing came up.

**Comment by x-falcon** [comment]
use the last version
https://github.com/x-falcon/Virtual-Hosts/releases/download/2.0.1/app-Github-release.apk
