### ISSUE TITLE
Use just one line to block all URL's

### ISSUE THREAD

**Issue by jsmeke** [x-falcon/Virtual-Hosts#32]
I use `127.0.0.1 *` to block ALL the URL's but is not working? How can I do that?

**Comment by x-falcon** [comment]
not support this.
You can use 
`127.0.0.1 .com   ` to block all *.com
`127.0.0.1 .net ` to block all *.net
`127.0.0.1 .org  ` to block all *.org
...

**Comment by kitkatloyalist** [comment]
hosts are not url

no path component may be blocked.

https://euthanizefools.pro/promulgate/video4.mp4

https:// is the protocol
euthanizefools.pro is the fqdn
/promulgate/video4.mp4 is the path

for this purpose we treat fqdn as host
