### ISSUE TITLE
自定义hosts

### ISSUE THREAD

**Issue by yym439** [x-falcon/Virtual-Hosts#33]
你好，我的hosts文件内容：
123.125.115.110 www.test.cn

设置好hosts后，通过手机浏览器访问www.test.cn无法跳转到123.125.115.110？显示无法访问

**Comment by x-falcon** [comment]
@yym439 你这个是百度的ip？ 这是由于百度有限制，不允许这个域名解析到这个ip，
你可以通过 adb shell 
`ping www.test.cn`  会发现是生效的
