### ISSUE TITLE
vivo R11 浏览器不生效

### ISSUE THREAD

**Issue by prife** [x-falcon/Virtual-Hosts#35]
配置hosts后，无论是R11自带的浏览器，还是安装的QQ浏览器都不生效。
adb shell ping确实是生效的

另外，参考【UC浏览器并不起作用】贴中的描述，关闭了QQ浏览器的云加速功能，依然不能生效。
似乎除了浏览器都生效了，请问这是为啥呢？

**Comment by x-falcon** [comment]
先试一下chrome ， uc的话，试试禁用预加载功能，关闭云端加速.
(你是怎么判断uc没生效的呢)

**Comment by x-falcon** [comment]
`106.2.69.113 a.com`
试试这条host记录，然后打开a.com,看看有没有显示一些信息

**Comment by prife** [comment]
谢谢x-falcon的热心回复哈，用了chrome浏览器就能生效了。准备给公司的同事推荐这个工具，再也不用root手机了~

感谢这么好的开源项目，希望后面有时间也能参与些开发~
