### ISSUE TITLE
No AndroidTV remote support on Android Oreo

### ISSUE THREAD

**Issue by croyd123** [x-falcon/Virtual-Hosts#36]
I'm using this app (v2.0.2.1) on AndroidTV (Oreo) on Nvidia Shield and when I select "Reselect host file", I can't navigate any of the menus with the remote. It use to work with Android N. Any chance of getting this supported? Although the shield allows the game controller to show a mouse pointer, it doesn't work as soon as the nav menu appears.

Thanks!

**Comment by x-falcon** [comment]
long click maybe not work on TV, I will make a button for fix the bug

**Comment by x-falcon** [comment]
Did you try long click the Reselect host file button ?
