### ISSUE TITLE
Firestick 4k storage permission denied

### ISSUE THREAD

**Issue by alligator5678** [x-falcon/Virtual-Hosts#37]
unable to set permission for storage on firestick 4k.  Navigate to applications/manage applications/Virtual Hosts/Permissions.  I then have to permissions to set, location and Storage.  Location works fine, I can allow or deny by pressing the "select" button.  Storage won't toggle between Deny and Allow, it justs makes a beep sound.  Once inside the app I am unable to navigate to any file to select as hosts proxy.

**Comment by x-falcon** [comment]
In fact, you don't have to give any permission. Just long click the select button

**Comment by alligator5678** [comment]
Thanks, long click gets to them point where I can choose the file.  I was able to download a file with a URL from the internet but was unable to use a file from local.  The file I wanted was in /sdcard/Download/myhostfile.txt/.  I was unable to enter the path properly.  How should I have entered the path?
