### ISSUE TITLE
error in gradle 

### ISSUE THREAD

**Issue by Minhasokz2** [x-falcon/Virtual-Hosts#38]
Failed to create parent directory 'C:\Users\Mr Rashid Minhas\Desktop\Virtual-Hosts\.gradle' when creating directory 'C:\Users\Mr Rashid Minhas\Desktop\Virtual-Hosts\.gradle\5.0-milestone-1\fileHashes'

**Comment by x-falcon** [comment]
This may be due to permission problems. Please try putting it in a directory other than C disk.

**Comment by Minhasokz2** [comment]
Its solved now But when gradle is completed  when I debug again nothing happens means app cannot be build nor tested(Run).

**Comment by Minhasokz2** [comment]
thanks every thing resolved finally.
