### ISSUE TITLE
accessing /system/etc/hosts

### ISSUE THREAD

**Issue by rosc2112** [x-falcon/Virtual-Hosts#4]
Can't access / from this program to start it up. I can browse / with other file mgrs. Maybe I'm supposed to make up a new hosts file in an accessible dir?
'
Not really sure what I'm supposed to do with this program. I'm a linux admin with 20+ yrs experience so I do know how /etc/hosts works. I use other vpn based tools (pkt sniffer, dns changer, pkt filter etc.. Would be nice to see a program utilizing all these vpn hacks in one app but thats a different subject :)

But I'm stumped. What file am I supposed to be opening just to start this program, and how?

**Comment by x-falcon** [comment]
Your guess is perfectly correct，
Just make a new hosts file or get from net, then put into accessible dir.
start app and click the big button to run. It will achieve the function of
modifying hosts.


2017年7月18日星期二，rosc2112 <notifications@github.com> 写道：
