### ISSUE TITLE
HTTP to HTTPS proxy

### ISSUE THREAD

**Issue by thany** [x-falcon/Virtual-Hosts#40]
Is it possible to add a feature that proxies HTTP to a HTTPS server?

Since this tool is oftenly used for development purposes, self-signed webites are quite commonplace. But mobile browsers in their infinite stupidity, downright block connections to self-signed websites. No way to "continue anyway" or similar, like usually possible on desktop browsers.

So the proxying feature would also have to ignore any certificate problems, which poses a security risk, but if it only works for the hosts in the hostsfile, I think it's totally okay.

**Comment by thany** [comment]
For other coming across this issue: it might also be worth noting that the only browser I've found that allows to "ignore" the warning, is Microsoft Edge for Android. Even though it's based on Blink...

**Comment by thany** [comment]
Closed means fixed/done? 😃

**Comment by x-falcon** [comment]
the app just change dns, not proxy
