### ISSUE TITLE
Re-select hosts file issue

### ISSUE THREAD

**Issue by Laicure** [x-falcon/Virtual-Hosts#41]
Hi!

Thanks for the great app!
It works well and very light on battery!

Anyway, I just have an issue regarding the **Re-select hosts file** button.

- Turning on the vpn switch, the **Re-select hosts file** is grayed but can still be clicked.
- ~**From Local** and **From Internet** seems to be redundant because I tried importing from a url using the **From Local** and it still works well.~
- Also, I think, it should be moved to the top instead at the bottom of the switch as it is not the main switch for turning on and off (for easier off-on).

Thanks!

**Comment by ChemBioScripting** [comment]
Sorry for the question, but have you compiled the app from its source code? I'm new in Android development; I never compiled a source code, and there isn't an explanation about how to compile this one on its repository. Can you give some instructions? A video tutorial would be great, but no one have ever provided it. Thanks a lot 👍

**Comment by Laicure** [comment]
@ChemBioScripting, seems off topic but hey 😉

I am also new to android development and I think there are tutorials about _how to compile from git using android studio_.

**Comment by ChemBioScripting** [comment]
Hello, @Laicure, I know: for that I apologized, but reading your post I seen that you have been able to compile it, making it working, and so my comment, thank you!

I will try to do a search with your suggested string but, if you know some good resource to understand exactly how to do it (better under Linux), you are really welcome!

Thanks a lot for your directions, and sorry for the off topic! Cheers

**Comment by Laicure** [comment]
Oh, I didn't compile it, I just used the latest release apk.

As for compiling, Android Studio alone can do the job though I am using Visual Studio 2017 with Android Development.

I will probably start with (this)[https://developer.android.com/training/basics/firstapp].

No worries for the off topic 😉

**Comment by ChemBioScripting** [comment]
Oh, in this case I misunderstood! Thanks a lot for the link: THIS will be my starting point with Android source code side, and soon its development too, I hope ❤🙌

Thanks so much, have a nice day! 🙂

**Comment by x-falcon** [comment]
@Laicure   From Internet Use For Down From Url,   It's more convenient.

**Comment by Laicure** [comment]
> @Laicure From Internet Use For Down From Url, It's more convenient.

Oh yes.
Well, I mean.
Both Local and URL works the same way in the latest app.

Sample:
**Local** down: http://winhelp2002.mvps.org/hosts.txt = success
**Url** down: http://winhelp2002.mvps.org/hosts.txt = still success

so I think, you may remove the local and url radio button because they work flawlessly the same.

Also, the **RE-SELECT HOSTS FILE** button is not truly disabled when Virtual Hosts is turned-on. You can still press it even though it is grayed.
