### ISSUE TITLE
FDroid?

### ISSUE THREAD

**Issue by Laicure** [x-falcon/Virtual-Hosts#42]
Can you release this on FDroid?

**Comment by x-falcon** [comment]
Is that very convenient? What steps are needed

**Comment by Laicure** [comment]
Not so convenient but it is a good way to gather more audience/users for your app like [DNS66](https://github.com/julian-klode/dns66).

Start here: https://blog.fossasia.org/publish-an-open-source-app-on-fdroid/

Closing this too ;)
