### ISSUE TITLE
Using a DNS server by default

### ISSUE THREAD

**Issue by Laicure** [x-falcon/Virtual-Hosts#43]
![Screenshot_20190325-185750](https://user-images.githubusercontent.com/8619566/54919195-1d9cf080-4f3b-11e9-981e-74d3aa2258c8.png)
I just checked that the app is using a DNS server (which should not, by default).
I think it is using Google DNS.

**Comment by x-falcon** [comment]
yes , it  use 8.8.8.8 by default.

**Comment by Laicure** [comment]
oh ok, can it be turned off?

**Comment by x-falcon** [comment]
I will add this feature

**Comment by Laicure** [comment]
yey thanks! I will wait for that.
I will close this now.

**Comment by Laicure** [comment]
Any way to turn it off and detect the current dns server by default?
