### ISSUE TITLE
How can I handle the tcp packet?

### ISSUE THREAD

**Issue by kings0527** [x-falcon/Virtual-Hosts#45]
First, good job.  Smart and Clear.

I had debug this code about UDP packet

Now, I need handle the tcp packet but no handle in the `TCPOutPut.java`

did `deviceToNetworkUDPQueue` had throw pass the VPN?

Plz give me one point to handle it.

**Comment by x-falcon** [comment]
default, not route tcp packet, need open it first

在 2019年7月1日星期一，kings0527 <notifications@github.com> 写道：

**Comment by x-falcon** [comment]
Now only the specified IP packet be Intercept，In order to save more electricity，and save resources.If you intercept all packets，Need to open in the settings.

**Comment by kings0527** [comment]
Thx, it's working.
I had donate use WeChat.
One coffee plz.
Maybe I need study the VPNService configure.

**Comment by x-falcon** [comment]
@kings0527 Thanks
