### ISSUE TITLE
Can you release on f-droid?

### ISSUE THREAD

**Issue by BobRoss12345** [x-falcon/Virtual-Hosts#47]
This was brought up before in #42, but it was closed. I use LineageOS without the Google Play store, so I can't download this app. I only use the F-Droid store to install apps. Can you add this app to F-Droid? The process is very straight forward, [here is the guide](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md#merge-requests). You just have to fill out some things about the app (the name, description, etc) and add a link to the github repo of the app. This will make F-Droid automatically build and release the app when new versions are released.

**Comment by x-falcon** [comment]
Ok i will try.

**Comment by fazlerabbi37** [comment]
Hello @x-falcon, are you still interested in publishing the app in F-Droid?

If yes, the quickest way to get started would be to open an [issue](https://gitlab.com/fdroid/rfp/-/issues/new) at the Request for packaging (RFP) repo. Also, take a look at [F-Droid: FAQ - App Developers](https://f-droid.org/en/docs/FAQ_-_App_Developers). Hope to see this app in Official F-Droid repo! :smile:

**Comment by trymeouteh** [comment]
Please publish and maintain the app on F-Droid

**Comment by fazlerabbi37** [comment]
@x-falcon seeing this closed as completed, where is the URL for the F-Droid repo? I would like to install the app from F-Droid. :smile: 

Also, please add a badge for F-Droid in the readme to make discovery easy. I can put a PR to do so if you can give me the URL.

**Comment by x-falcon** [comment]
It's coming soon
