### ISSUE TITLE
VPN Hosts Not Working Properly, Not Blocking Game And Browser Traffic!

### ISSUE THREAD

**Issue by hari01584** [x-falcon/Virtual-Hosts#48]
**I Dont  Know Why This Is Happening But Somehow VPN Hosts Doesnt Work Nice For ME!!**
_The Problem Is That Even After Setting Hosts Go To Work, It Doesnt Block Game Traffic, Tho WHen I Try To Open Website In Browser It Works(in google chrome), But In Mi Browser, The Site Still Opens!_

This Is Annoying Bug I Think! NEEd TO BE FIXED ASAP
Regards,
~Agent_Orange

**Comment by x-falcon** [comment]
![Screenshot_20191217-083516_Settings](https://user-images.githubusercontent.com/5160100/70954477-5328d180-20a8-11ea-9f0d-4f51d4a4cbbe.jpg)

please close data compresion or Related Services.

**Comment by hari01584** [comment]
Let us assume, that thing fixed the issue, but still what about application? I have this game, in which I Wana perform dns poisoning, the game is using https protocol to communicate with it's real server, but I'm trying to dns spoof to my own fake domain in order to change some traffic data, well is it possible!

**Comment by hari01584** [comment]
Hello, sorry for everything I have been talking about, well luckyily I found the exact problem!
I'm starting a new issue with more accurate data, and things! Thanks for listening me here!
