### ISSUE TITLE
Infinite Loop When Trying To Perform A Redirect Dns Poisoning!

### ISSUE THREAD

**Issue by hari01584** [x-falcon/Virtual-Hosts#49]
So let me get my point clear, I'm trying to poison a game by dns poisoning, so what I'm trying to do is that consider I have three websites, A, X And Y in format like (A.com, etc), now let us assume the site X is of game site, what I'm trying to do is to setup a vpn using virtual hosts and inject the IP of site A (which is attacker's site), so that the game will contact site A as a whole, but then the site A will check what game is requesting, if it is a request to get no of golds and currency of user then the site will smartly inject its own response and send it to client, but if that might not be the case, then the site will simply send a redirect request following to the original site (Site X Or Y)

Y is canonical name of site X, both refer to same place, but they are canonical names, ie let x and y be
X - server.xyzgames.com
Y - gdh22hs32.cloudfront.com

Now here comes the issue, when going to site Y through a redirect done by Site A, the game request backs the site Y again, this in turn once again inject the Y's ip address with Site A's Ip, and hence an infinite Loop is formed, which results in no receiving of data and on server site infinite requests!

Is there any way to fix this problem? Also I have fully imported and using your codes right now, they are amazing!

**Comment by x-falcon** [comment]
can intercept the redirect response packet, then change the host name with domain dynamic.

**Comment by hari01584** [comment]
I don't really get it, can ya please elaborate? With some examples? Or some
sample codes and settings I need to tweak in order to get it?
Regards,
~Agent_Orange

**Comment by hari01584** [comment]
Hello? Any reply? I'm waiting!

**Comment by x-falcon** [comment]
This can be a very complicated job

**Comment by hari01584** [comment]
I understand so! But even so anything would be preferable!

**Comment by hari01584** [comment]
Made tweaks to prevent loopback, and using Hexene (Virtual Hosts using VPN Interceptor Library)  we can even directly modify the source and destination address according to situation (Needs to recalculate IP and TCP checksums tho). therefore I am closing this issue.
