### ISSUE TITLE
can't use threema web

### ISSUE THREAD

**Issue by brunoherrera** [x-falcon/Virtual-Hosts#50]
I think it's something related to webrtc, but I'm not sure. Threema web doesn't work, even if my hosts file is empty, so I'm not really blocking it, it's something else. Can you check on that please? Or maybe add an option to exclude apps from connecting through local vpn

**Comment by x-falcon** [comment]
webrtc use p2p, vpn may not support

**Comment by brunoherrera** [comment]
aaah, makes sense, thanks!
