### ISSUE TITLE
How to make auto select host without pressing "re select host" and search host

### ISSUE THREAD

**Issue by GuckTubeYT** [x-falcon/Virtual-Hosts#51]
How to make auto select host without pressing "re select host" and search host

And then just press "turn on"

**Comment by x-falcon** [comment]
just click the big button

**Comment by GuckTubeYT** [comment]
no, i mean make embedded virtual host, when i install the app, i just press turn on

**Comment by GuckTubeYT** [comment]
nevermind, closie issue
