### ISSUE TITLE
No longer working - mi a1 February 2020 security patch

### ISSUE THREAD

**Issue by wodgey** [x-falcon/Virtual-Hosts#52]
As per the title, DNS requests no longer complete after latest security patch.

What logs\info do you need, to provide assistance?

**Comment by x-falcon** [comment]
plesse provide android version

**Comment by wodgey** [comment]
I'm using the stock Xiaomi pie ROM. It worked right up until the latest security patch. I have not performed any other diagnostics other than posting an issue here. I have not completed a factory reset yet. I would rather not have to do this but I can do if necessary.
