### ISSUE TITLE
Not working with Chrome, Samsung Internet on Android 9

### ISSUE THREAD

**Issue by kainjinez** [x-falcon/Virtual-Hosts#54]
I checked with DuckDuckGo browser then it still work on my device.
But Chrome & Samsung Internet doesn't. I searched on closed issues, you said that it related to Async DNS.
Any chance in future you will fix it? Because it feel long from first time problem happens.
Thanks.

**Comment by nautatva** [comment]
https://amp.reddit.com/r/VPN/comments/boe2b1/android_chrome_not_using_vpn_pushed_dns/

The link in comment should help: https://www.xda-developers.com/fix-dns-ad-blocker-chrome/
