### ISSUE TITLE
小米8，adb进去 ping 目标域名 可以解析到通过配置文件设置的ip，但是浏览器访问目标域名不生效

### ISSUE THREAD

**Issue by sunhao0313** [x-falcon/Virtual-Hosts#55]
如题，请作者帮忙分析下，谢谢~

**Comment by x-falcon** [comment]
Open Chrome, type in chrome://flags
search for async DNS resolver (#enable-async-dns) and choose disabled in the drop down menu.
(Otherwise chrome could use a built in dns resolver which does not block ads

**Comment by sunhao0313** [comment]
Thanks [cid:image001.png@01D61708.E79AFE00] ，it works.

Best wishes
发件人: xfalcon [mailto:notifications@github.com]
发送时间: 2020年4月20日 6:43
收件人: x-falcon/Virtual-Hosts
抄送: 孙浩; Author
主题: Re: [x-falcon/Virtual-Hosts] 小米8，adb进去 ping 目标域名 可以解析到通过配置文件设置的ip，但是浏览器访问目标域名不生效 (#55)


Open Chrome, type in chrome://flags
search for async DNS resolver (#enable-async-dns) and choose disabled in the drop down menu.
(Otherwise chrome could use a built in dns resolver which does not block ads
