### ISSUE TITLE
Android TV

### ISSUE THREAD

**Issue by Evilmnkey** [x-falcon/Virtual-Hosts#60]
Hi,
    any plans to make this available for android TV? I am currently running the Shield TV pro 2019 with the latest update. When I sideload the app it installs fine and i can select a host file but it just crashes after a min or two

Android Version 9

THank you

**Comment by x-falcon** [comment]
please long click the select file button, use net work file

**Comment by Evilmnkey** [comment]
how is the network file better than the local host file?
I will give it a shot later today, thanks

**Comment by Evilmnkey** [comment]
Using network file and same issue happens. Just stops working
