### ISSUE TITLE
获取网络文件部分建议添加允许未加密的连接

### ISSUE THREAD

**Issue by xszx** [x-falcon/Virtual-Hosts#68]
我尝试了你的程序，在高版本的android中，联网失败报错:Cleartext HTTP traffic to xxx not permitted。

引用：为保证用户数据和设备的安全，Google针对下一代 Android 系统(Android P) 的应用程序，将要求默认使用加密连接，这意味着 Android P 将禁止 App 使用所有未加密的连接，因此运行 Android P 系统的安卓设备无论是接收或者发送流量，未来都不能明码传输，需要使用下一代(Transport Layer Security)传输层安全协议，而 Android Nougat 和 Oreo 则不受影响。

解决方案：
1：允许未加密的连接。
在AndroidManifest.xml配置文件的<application>标签中直接插入
android:usesCleartextTraffic="true"

2.允许不安全的证书。

目前我编译了你的代码，添加了方案1的代码，能在高版本的android系统中正常获取网络文件。

**Comment by Hamammal** [comment]
- @![w.png](https://github.com/x-falcon/Virtual-Hosts/assets/148014926/ef274113-1ea2-4380-ac93-2b0837b94920)
