### ISSUE TITLE
hosts file ignored on andoird 13

### ISSUE THREAD

**Issue by djamadeus** [x-falcon/Virtual-Hosts#74]
Hi, i just bought the app via the app store. Created a simple hosts file for one domain to a specifix IP addr. After VPN is enabled, Chrome, Firefox as well as ping on Terminus still resolve to the original IP..

**Comment by x-falcon** [comment]
> 

please show me the hosts file

**Comment by SonicFan2020-best** [comment]
Same issue here.

**Comment by x-falcon** [comment]
![20230530-110651](https://github.com/x-falcon/Virtual-Hosts/assets/5160100/c22971fc-acbd-4ca2-bfae-6a2ed553a8fa)
test ok on android 13

**Comment by djamadeus** [comment]
![image](https://github.com/x-falcon/Virtual-Hosts/assets/5102894/7677fb6b-941b-4d68-bc82-b9cdf4712841)

**Comment by djamadeus** [comment]
still doesn't work for me. also not after android update

**Comment by lhy7889678** [comment]
It seems that Android 13 will turn on Private DNS by default, which will override the hosts specified in Virtual Hosts. After turning it off (it should be somewhere in your phone settings), the app works again.
