### ISSUE TITLE
Toggle from tasker

### ISSUE THREAD

**Issue by jk3us** [x-falcon/Virtual-Hosts#8]
Is there a way to toggle the state from tasker? Or could this be added?

**Comment by x-falcon** [comment]
will add it next version

**Comment by x-falcon** [comment]
Please try new version. @jk3us

**Comment by jk3us** [comment]
I see you added a taskbar icon (which is nice), but I was asking about tasker integration, either by writing a tasker plugin (http://tasker.dinglisch.net/developers.html) or just exposing intents to turn on/off or toggle the state that I could call from a tasker task.
