### ISSUE TITLE
internet lockdown after being continuously enabled for a few days

### ISSUE THREAD

**Issue by ashjas** [x-falcon/Virtual-Hosts#9]
I have been experiencing this issue, that after being enabled for a few days continuously , there is no internet at all.. no apps can access internet.
If i do ping google.com from within adb shell, there is no response:
`shell@douglas:/ $ ping google.com
ping: unknown host google.com
`
But things are back to normal, when i disable-reenable the vpn hosts.

I am on amazon fire HD 2017 tablet with Fire OS 5.4.0.0 (Based on Android 5.1.1)

Not saying, there is a bug in the app itself as amazon could be the culprit, as its heavily modified Fire OS from the stock Android.

I am attaching logcats from two sessions, when i start facing the issue. Please look, if something is wrong at the vpn hosts side.

Thank you for this app!
[FireTabVpnHost-EnabledNoInternet](https://gist.github.com/ashjas/154798f70f2e5afe2c8f6ae60f7effda)
[FireTabVpnHost-EnabledNoInternet2](https://gist.github.com/ashjas/e98fe9afbd8cdb8e65fba39dea0016ae)

**Comment by x-falcon** [comment]
Thank you for feedback,I will try check about this problem

**Comment by x-falcon** [comment]
@ashjas please try the new verson, may fix the bug

**Comment by ashjas** [comment]
I've already updated to the newer version. Will report back if I experience same issue. Thanks for the support.
